CREATE TABLE IF NOT EXISTS USERS (
	USER_ID BIGINT NOT NULL,
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	USERNAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	ENABLED BOOLEAN NOT NULL,
	PRIMARY KEY(USER_ID)
);

CREATE TABLE IF NOT EXISTS ROLES (
	ROLE_ID BIGINT NOT NULL,
	NAME VARCHAR(255),
	PRIMARY KEY(ROLE_ID)
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
	USER_ID BIGINT NOT NULL,
	ROLE_ID BIGINT NOT NULL,
	PRIMARY KEY(USER_ID, ROLE_ID)
);

CREATE TABLE IF NOT EXISTS PRIVILEGES (
	PRIVILEGE_ID BIGINT NOT NULL,
	NAME VARCHAR(255),
	PRIMARY KEY(PRIVILEGE_ID)
);

CREATE TABLE IF NOT EXISTS ROLES_PRIVILEGES (
	ROLE_ID BIGINT NOT NULL,
	PRIVILEGE_ID BIGINT NOT NULL,
	PRIMARY KEY(ROLE_ID, PRIVILEGE_ID)
);

